---
- name: (tasks/config_prod.yml) - Configure Prod Host
  block:
    - name: (tasks/config_prod.yml) - Echo a string
      ansible.builtin.debug:
        msg: "Configure Prod Envirionment"

    - name: (tasks/config_prod.yml) - Install gunicorn Python modules
      ansible.builtin.pip:
        name:
          - gunicorn
        state: present
        executable: pip3
      become: true
      # https://developers.redhat.com/articles/2023/08/17/how-deploy-flask-application-python-gunicorn#the_application
      # Nginx can’t communicate directly with Flask app.
        # It can’t execute the application.
        # We need WSGI server (Gunicorn) to communicate between server and flask app.

    - name: (tasks/config_prod.yml) - Install Podman
      ansible.builtin.dnf:
        name:
          - podman
        update_cache: false
        state: present
      become: true

    - name: (tasks/config_prod.yml) - Build container
      ansible.builtin.include_tasks: build_container.yml
      register: container_result

    - name: (tasks/config_prod.yml) - Deploy proccess
      ansible.builtin.include_tasks: deploy_process.yml
      when: check_image_result.status[0] == "success"

    - name: (tasks/config_prod.yml) - Set config result
      set_fact:
        config_result:
          status: "success"
          message: "Config completed successfully"
      when: deployment_result.rc == 0

    # - name: Install nginx
    #   ansible.builtin.include_tasks: install_nginx.yml
