---
- name: Configure Dev Host
  block:
    - name: Echo a string
      ansible.builtin.debug:
        msg: "Configure Dev Envirionment"

    - name: Check if Flask process is running
      ansible.builtin.shell: |
        pgrep -f "python3 flask_app.py"
      register: flask_process # <- Registers the command output.
      ignore_errors: true
      changed_when: false # Explicitly say task never changes system state, which is appropriate for a command that only retrieves information.

    - name: Display Flask status
      ansible.builtin.debug:
        msg: "( {{ flask_process.stdout }} ' - ' {{ flask_process.rc }} ) Flask is {{ 'running' if flask_process.rc == 0 else 'not running' }}"


    # The "nohup" command, short for "no hang up," is meant to run processes that continue executing after the user logs out or the terminal session ends.
    - name: Start Flask app
      ansible.builtin.shell:
        chdir: "{{ deploy_flask_app_build_path }}"
        cmd:  nohup python3 flask_app.py > /home/ec2-user/flask.log 2>&1 &
      when: flask_process.rc != 0
      changed_when: flask_process.rc != 0 # <- Uses the return code to define when the task has changed.
