---
- name: Configure Dev Host --> (tasks/config_dev.yml in {{ envirionment }})
  block:
    - name: Echo a string --> (tasks/config_dev.yml in {{ envirionment }})
      ansible.builtin.debug:
        msg: "Configure Dev Envirionment"

    - name: Deploy proccess --> (tasks/config_dev.yml in {{ envirionment }})
      ansible.builtin.include_tasks: deploy_process.yml
