---
- name: (tasks/config_dev.yml) - Configure Dev Host
  block:
    - name: (tasks/config_dev.yml) - Echo a string
      ansible.builtin.debug:
        msg: "Configure Dev Envirionment"

    - name: (tasks/config_dev.yml) - Deploy proccess
      ansible.builtin.include_tasks: deploy_process.yml

    - name: (tasks/config_dev.yml) - Set config result
      set_fact:
        config_result:
          status: "success"
          message: "Config completed successfully"
      when: deployment_result.rc == 0
