---
- name: Configure Dev Host
  block:
    - name: Echo a string
      ansible.builtin.debug:
        msg: "Configure Dev Envirionment"

    - name: Deploy proccess
      ansible.builtin.include_tasks: deploy_process.yml
