---
- name: Configure Prod Host --> (tasks/config_prod.yml in {{ envirionment }})
  block:
    - name: Echo a string --> (tasks/config_prod.yml in {{ envirionment }})
      ansible.builtin.debug:
        msg: "Configure Prod Envirionment"

    - name: Install gunicorn Python modules --> (tasks/config_prod.yml in {{ envirionment }})
      ansible.builtin.pip:
        name: gunicorn
        state: present
        executable: pip3
      become: true

      # https://developers.redhat.com/articles/2023/08/17/how-deploy-flask-application-python-gunicorn#the_application
      # Nginx can’t communicate directly with Flask app.
        # It can’t execute the application.
        # We need WSGI server (Gunicorn) to communicate between server and flask app.

    - name: Install Podman --> (tasks/config_prod.yml in {{ envirionment }})
      ansible.builtin.dnf:
        name:
          - podman
        update_cache: false
        state: present
      become: true

    # TODO: Add conditional "If Clone GitHub has changes"
    - name: Build container --> (tasks/config_prod.yml in {{ envirionment }})
      ansible.builtin.include_tasks: build_container.yml
      register: build_container_result

    - name: Deploy proccess --> (tasks/config_prod.yml in {{ envirionment }})
      ansible.builtin.include_tasks: deploy_process.yml
      when: build_container_result is succeeded

    # - name: Install nginx
    #   ansible.builtin.include_tasks: install_nginx.yml
