---
- name: (tasks/config_dev.yml) - Configure Dev Host
  block:
    - name: (tasks/config_dev.yml) - Echo a string
      ansible.builtin.debug:
        msg: "Configure Dev Envirionment"

    - name: (tasks/config_dev.yml) - Deploy proccess
      ansible.builtin.include_tasks: deploy_process.yml
