---
- name: Install gunicorn
  block:
    - name: Install gunicorn Python modules
      ansible.builtin.pip:
        name:
          - gunicorn
        executable: pip3

    - name: Install Podman
      ansible.builtin.dnf:
        name:
          - podman
        update_cache: false
        state: present
      become: true