---
- name: (tasks/main.yml) - Deploy flask application
  block:
    - name: (tasks/main.yml) - Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true

    - name: (tasks/main.yml) - Install Python3, pip, and git
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: (tasks/main.yml) - Install Python modules
      ansible.builtin.pip:
        name:
          - flask
        executable: pip3

    - name: (tasks/main.yml) - Clone GitHub repository
      ansible.builtin.git:
        repo: https://github.com/Daniel-Perrinez/Ansible_POC.git
        dest: /home/ec2-user/Ansible_POC
        version: main
        clone: true
        update: true

    - name: (tasks/main.yml) - Configure host for {{ envirionment }}
      ansible.builtin.include_tasks: config_{{ envirionment }}.yml
