---
- name: Deploy flask application --> (tasks/main.yml (tasks/main.yml in {{ envirionment }}))
  block:
    - name: Update all packages --> (tasks/main.yml in {{ envirionment }})
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true

    - name: Install Python3, pip, and git --> (tasks/main.yml in {{ envirionment }})
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Install Python modules --> (tasks/main.yml in {{ envirionment }})
      ansible.builtin.pip:
        name:
          - flask
        executable: pip3

    - name: Clone GitHub repository --> (tasks/main.yml in {{ envirionment }})
      ansible.builtin.git:
        repo: https://github.com/Daniel-Perrinez/Ansible_POC.git
        dest: /home/ec2-user/Ansible_POC
        version: main
        clone: true
        update: true

    - name: Configure host --> (tasks/main.yml in {{ envirionment }})
      ansible.builtin.include_tasks: config_{{ envirionment }}.yml
