--- 
  - name: ansible_play
    hosts: VMWare_RHEL_9_3
    connection: local

    tasks:
      # - name: Update all packages using yum
      #   shell: yum -y update
      #   become: true
      
      - name: Check nameservers
        shell: |
          cat /etc/resolv.conf  > /dev/null
        register: result

      - name: Test Echo
        shell: |
          echo "------- wow -------"  > /dev/null
        # shell: |
        #   hostnamectl set-hostname RHEL_9.3_Ansible_Tower_04_02_2024
        register: result
        # become: true
      
      - name: Display the output
        debug:
          msg: "{{ result.stdout_lines }}"
          

