---
- name: Configure Flask app
  hosts: Dev
  become: true
  remote_user: ec2-user
  gather_facts: true

  vars:
    region: us-east-1
    security_group: flask_sg

  # tasks:
    # - name: Deploy app to Dev
    # - name: Update dependencies if needed
    # - name: Test app is responsive

    # - name: If Dev deployment has passed test, then deploy to staging
    # - name: If staging passes, then Deploy app to production.
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true

    - name: Install Python3, pip, and git
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Install Flask
      ansible.builtin.pip:
        name: flask
        executable: pip3

    - name: Clone GitHub repository
      ansible.builtin.git:
        repo: https://github.com/Daniel-Perrinez/Dockerized_Flask_Website.git
        dest: /home/ec2-user/flask_app
        version: main
        clone: true
        update: true

    - name: Install and configure Nginx
      block:
        - name: Install Nginx
          ansible.builtin.dnf:
            name: nginx
            state: present

        # - name: Configure Nginx
        #   ansible.builtin.template:
        #     src: ./nginx.conf.j2
        #     dest: /etc/nginx/nginx.conf
        #   notify: Restart Nginx

    # The "nohup" command, short for "no hang up," is meant to run processes that continue executing after the user logs out or the terminal session ends.
    - name: Start Flask app
      ansible.builtin.shell: |
        nohup python3 /home/ec2-user/flask_app/app.py > /home/ec2-user/flask.log 2>&1 &

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
