---
argument_specs:
  main:
    version_added: 2.0.0
    short_description: Deploy flask app in AWS.
    options:
      deploy_flask_app_bastion_host_username:
        description: Username for the bastion host SSH user.
        type: str
        required: True
      deploy_flask_app_bastion_instance_id:
        description: The instance Id of the EC2 bastion virtual machine.
        type: str
        required: True
        version_added: 2.1.0
      deploy_flask_app_bastion_ssh_private_key_path:
        description: The path to ssh private key file to use to connect to the bastion host.
        type: path
        required: True
        version_added: 2.1.0
      deploy_flask_app_private_subnet_id:
        description: Private subnet id of the bastion host.
        type: str
        required: True
      deploy_flask_app_vpc_id:
        description: vpc id for the host.
        type: str
        required: True
      deploy_flask_app_rds_host:
        description: The RDS endpoint address.
        type: str
        required: True
      deploy_flask_app_rds_dbname:
        description: The RDS Database name.
        type: str
        required: True
      deploy_flask_app_rds_master_username:
        description: Master username of the RDS backend.
        type: str
        required: True
      deploy_flask_app_rds_master_password:
        description: Master password of the RDS backend.
        type: str
        required: True
      deploy_flask_app_number_of_workers:
        description: Number of instances to create.
        type: int
      deploy_flask_app_workers_instance_type:
        description: RC2 instance type for workers.
        type: str
        required: True
      deploy_flask_app_workers_user_name:
        description: Username for the workers.
        type: str
        required: True
      deploy_flask_app_listening_port:
        description: Load balancer port.
        type: int
        required: True
      deploy_flask_app_force_init:
        description: A boolean value True to force init the app and False to not force init.
        type: bool
        required: True
      deploy_flask_app_config:
        description: A dict of config parameterys for the app.
        type: dict
        required: True
        options:
          env:
            description: Flask env.
            type: str
            required: True
          admin_user:
            description: App config's admin username.
            type: str
            required: True
          admin_password:
            description: App config's admin password.
            type: str
            required: True
          app_dir:
            description: App directory.
            type: str
            required: True
