---
- name: Add new service account
  hosts: Dev, Prod
  become: true
  remote_user: ec2-user
  gather_facts: true
  # roles:
  #   - deploy_flask_app
  tasks:
    - name: Include Role - deploy_flask_app
      ansible.builtin.include_role:
        name: deploy_flask_app
