---
envirionment: dev
ansible_user: ec2-user
ansible_ssh_private_key_file: ../../../creds/id_rsa # ansible_password: 123
deploy_flask_app_build_path: "Ansible_POC/AWS_Intro_to_Ansible/3-Advanced/Flask_app"
process_name: "python3 flask_app_dev.py"
# deploy_flask_app_image_name: "flask_pod"
# deploy_flask_app_image_tag: "1.0.0"
# deploy_flask_app_build_path: "Ansible_POC/AWS_Intro_to_Ansible/3-Advanced/Flask_app"
